# This workflow updates the package version and publishes to NPM when a release is created
# Uses OIDC Trusted Publishing for enhanced security (no long-lived secrets)
#
# Setup required:
# 1. Go to https://www.npmjs.com/package/node-red-contrib-gemini
# 2. Click Settings → Publishing Access → Add Trusted Publisher
# 3. Configure with:
#    - Provider: GitHub Actions
#    - Repository Owner: calrock27
#    - Repository Name: node-red-contrib-gemini
#    - Workflow Name: npm-publish.yml
# 4. Ensure your NPM account has 2FA enabled
#
# The release tag should be a semantic version (e.g., v1.0.2 or 1.0.2)

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Extract version from release tag
        id: version
        run: |
          # Remove 'v' prefix if present
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Extracted version: ${VERSION}"

      - name: Update package.json version
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version
          echo "Updated package.json to version ${{ steps.version.outputs.version }}"

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit version change
        run: |
          git add package.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }} || echo "No changes to push"

      - name: Install dependencies
        run: npm ci

      - name: Run smoke tests
        run: npm test

      - name: Verify package contents
        run: npm pack --dry-run

      - name: Publish to NPM with provenance
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
